[platformio]
src_dir = ./

[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube
build_flags =
  -D STM32G474xx
  -ICore/Inc
  ; -IDrivers/CMSIS/Include
  ; -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
  ; -IDrivers/STM32G4xx_HAL_Driver/Inc
  ; -IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy
build_src_filter = +<Core/Src> +<startup_stm32g474xb.s>
board_build.ldscript = ./stm32g474retx_flash.ld

upload_protocol = stlink
debug_tool = stlink
